apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: production
  labels:
    app: devops-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-app
          image: your-dockerhub-username/devops-pipeline-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres-service.database.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "appdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              value: "postgres"
